# version: '3.8'

x-logging-defaults: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  auction-bot:
    container_name: auction-bot
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./backup:/app/backup
    command: ['python3', 'bot.py']
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f bot.py || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    x-logging-defaults: *default-logging
